// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBHlyZkBGrhoFepTe1A6DdyZzh7km4JfmI',
    appId: '1:690014095278:web:d698a71e52ba168de52a3f',
    messagingSenderId: '690014095278',
    projectId: 'my-calendar-fff18',
    authDomain: 'my-calendar-fff18.firebaseapp.com',
    databaseURL: 'https://my-calendar-fff18-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'my-calendar-fff18.appspot.com',
    measurementId: 'G-RE9T5TYN90',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDT0hhKfzACxqblu7fXVnZiJO1PkRb5aaE',
    appId: '1:690014095278:android:ee975764ff606776e52a3f',
    messagingSenderId: '690014095278',
    projectId: 'my-calendar-fff18',
    databaseURL: 'https://my-calendar-fff18-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'my-calendar-fff18.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAaimtYk4SPyKYpL2CbD6-r2kpnRUxLItA',
    appId: '1:690014095278:ios:71500107d88850f3e52a3f',
    messagingSenderId: '690014095278',
    projectId: 'my-calendar-fff18',
    databaseURL: 'https://my-calendar-fff18-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'my-calendar-fff18.appspot.com',
    iosClientId: '690014095278-698deh4mipsre2v1vdvgqfs24s8iuti8.apps.googleusercontent.com',
    iosBundleId: 'com.example.myCalendarTFC',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAaimtYk4SPyKYpL2CbD6-r2kpnRUxLItA',
    appId: '1:690014095278:ios:9728610b220636d6e52a3f',
    messagingSenderId: '690014095278',
    projectId: 'my-calendar-fff18',
    databaseURL: 'https://my-calendar-fff18-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'my-calendar-fff18.appspot.com',
    iosClientId: '690014095278-om901it947lllf8ksk15hntp7d7lg6g2.apps.googleusercontent.com',
    iosBundleId: 'com.example.myCalendar',
  );
}
